site_name: proffssv.site
site_url: https://proffssv.site
repo_url: https://github.com/Serg2206/proffssv.site
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
  icon:
    logo: material/account-heart
  favicon: assets/favicon.png

extra:
  social:
    - icon: material/youtube
      link: https://www.youtube.com/@SSVproff-22.06
      name: YouTube
    - icon: material/coffee
      link: https://www.buymeacoffee.com/ssvproff
      name: Buy Me a Coffee
    - icon: material/book-open-variant
      link: https://github.com/Serg2206/proffssv.site
      name: GitHub

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

nav:
  - Главная: index.md
  - О проекте: about.md
  - Поддержать: support.md
  - Консультации: consultations.md
  - Рекомендую: recommend.md
